name: Marketing Idea
description: Suggest an idea to the approach to spread the use of the project
labels: [marketing]
body:
    - type: textarea
      id: description
      attributes:
          label: Is your feature request related to a problem? Please describe.
          description: A clear and concise description of what the problem is.
      validations:
          required: true
    - type: textarea
      id: context
      attributes:
          label: Additional context
          description: Add any other context or screenshots about the feature request here.
          placeholder: Additional context
    - type: checkboxes
      id: terms
      attributes:
          label: Code of Conduct
          description: By submitting this issue, you agree to follow our
              [Code of Conduct](https://github.com/nanorepublica/django-prodserver/blob/main/.github/CODE_OF_CONDUCT.md).
          options:
              - label: I agree to follow this project's Code of Conduct
                required: true
    - type: checkboxes
      id: willing
      attributes:
          label: Are you willing to resolve this issue by submitting a Pull Request?
          description: Remember that first-time contributors are welcome! 🙌
          options:
              - label: Yes, I have the time, and I know how to start.
              - label: Yes, I have the time, but I don't know how to start. I would need guidance.
              - label: No, I don't have the time, although I believe I could do it if I had the time...
              - label: No, I don't have the time and I wouldn't even know how to start.
    - type: markdown
      attributes:
          value: 👋 Have a great day and thank you for the idea!
